name: Build Snap

on:
  push:
    branches:
      - dev
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-snap:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: snapcore/action-build@v1
        id: snapcraft

      - uses: actions/upload-artifact@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        with:
          name: 'artifacts'
          path: ${{steps.snapcraft.outputs.snap}}
      
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          name: Ubuntu Desktop Provision ${{ github.ref_name }}
          draft: false
          generate_release_notes: false
          files: |
            ${{steps.snapcraft.outputs.snap}}

